osx_image: xcode8.2
dist: trusty
sudo: false

language: node_js
node_js:
  - "6"

install:
  - npm install

before_script:
  - npm run build
  
script:
- npm run test-travis

cache:
  directories:
  - node_modules